background {
    monitor =
    path = /usr/share/wallpapers/EndeavourOS/contents/screenshot.png
    blur_passes = 3
    brightness = 0.42
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgba(cdd6f4ff)
    font_size = 72
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 80
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%A, %d %B %Y')"
    color = rgba(cba6f7ff)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 0, 15
    halign = center
    valign = center
}

# Input Field
input-field {
    monitor =
    size = 280, 54
    outline_thickness = 2
    outer_color = rgba(cba6f7ff)
    inner_color = rgba(11111bcc)
    font_color = rgba(cdd6f4ff)
    check_color = rgba(a6e3a1ff)
    fail_color = rgba(f38ba8ff)
    dots_size = 0.25
    dots_spacing = 0.22
    fade_on_empty = false
    placeholder_text = Password...
    position = 0, -90
    halign = center
    valign = center
}
